- routes/transaction.js
Queries for multiple transactions `/transaction/details/["txHash1","txHash2"]` do not have the same data for `vin` compared to queries for a single transaction `/transaction/details/txHash`.
Differences:
- Missing `legacyAddress`, `cashAddress`, `value`
- Should delete `addr`, `valueSat`, `doubleSpentTxID`
This commit fixes that by applying the same processing of single transactions to the query for multiple transactions.
> Adds inputs processing for queries with multiple transactions

- routes/address.js
- routes/block.js
- routes/blockchain.js
- routes/control.js
- routes/generating.js
- routes/health-check.js
- routes/index.js
- routes/mining.js
- routes/network.js
- routes/rawtransactions.js
- routes/transaction.js
- routes/util.js
- test/RawTransactions.js
- test/block.js
- test/blockchain.js
- test/control.js
- test/generating.js
- test/health-check.js
- test/mining.js
- test/network.js
- test/transaction.js
- test/util.js
This PR does not change any functionality. It simply lints the existing routes and test files with the linting rules that were added in the last PR.
> Routes and Tests Have Been Linted

- test/dataRetrieval.js
> Update expected return values

- test/RawTransactions.js
- test/address.js
- test/block.js
- test/blockchain.js
- test/control.js
- test/generating.js
- test/health-check.js
- test/mining.js
- test/network.js
- test/payloadCreation.js
- test/transaction.js
> Wormhole merge2b

- public/bitcoin-com-rest-v1.json
- test/dataRetrieval.js
This commit backs out commits 1e09b61 and afaa91d in the `stage` branch because they are breaking the build. This commit also fixes the Swagger GUI for the Wormhole endpoints in the Raw Transactions library, as well as `balancesForAddress` and `balancesForId` from the Data Retrieval library.
> Stage working

- public/bitcoin-com-rest-v1.json
- routes/dataRetrieval.js
- routes/payloadCreation.js
* payloadCreation/freeze/toAddress/propertyId/amount
* payloadCreation/unfreeze/toAddress/propertyId/amount
> Add freeze/unfreeze support for stable coin

- README.md
- package.json
- public/bitcoin-com-rest-v1.json
- routes/dataRetrieval.js
- routes/payloadCreation.js
* /payloadCreation/freeze
* /payloadCreation/unfreeze
* /dataRetrieval/frozenBalance
* /dataRetrieval/frozenBalance
* /dataRetrieval/frozenBalanceForId
> Add endpoints for stable-coin support

- .gitignore
- README.md
- package.json
- test/RawTransactions.js
- test/dataRetrieval.js
These series of commits are not really code commits. We are trying to get Travis CI to successfully pass integration tests.
> Testing Travis CI

- .gitignore
- README.md
- package.json
- test/RawTransactions.js
- test/dataRetrieval.js
This is the same PR that had tests passing yesterday (10/18/18) and it also restores the original behavior of address.js.
> Restore tests and original functionality of address.js

- app.js
- public/bitcoin-com-rest-v1.json
- routes/v1/address.js
- routes/v1/slp.js
- routes/v2/address.js
> List all SLP tokens.

- package.json
- public/bitcoin-com-rest-v1.json
- routes/v1/slp.js
* `slp/balancesForAddress/:address`
> slp balance by address

- package.json
- public/bitcoin-com-rest-v1.json
- routes/v1/slp.js
* `slp/balancesForAddress/:address`
> Show SLP balances for address

- package.json
- public/bitcoin-com-rest-v1.json
- routes/v1/slp.js
* `slp/address/convert/{address}`
> SLP addr conversion

- public/bitcoin-com-rest-v1.json
- routes/v1/address.js
- routes/v1/block.js
- routes/v1/blockchain.js
- routes/v1/dataRetrieval.js
- routes/v1/slp.js
- routes/v2/dataRetrieval.js
- routes/v2/rawtransactions.js
- routes/v2/util.js
- test/block.js
- test/dataRetrieval.js
- test/slp.js
* simplify path
* add tests
* return info about token
> SLP updates

- routes/v1/payloadCreation.js
- test/payloadCreation.js
This PR limits the crowdsale deadline to 100 years in the future.
> Adding validation for crowdsale deadline

- package.json
- public/bitcoin-com-rest-v1.json
- routes/v1/slp.js
Initial balancesForToken endpoint. Missing tests.
> Balances for all holders of a token

- dist/app.js
- tsconfig.json
* common js modules instead of es6
> common js modules instead of es6

- dist/routes/v2/control.js
- dist/routes/v2/dataRetrieval.js
- dist/routes/v2/mining.js
- src/routes/v2/block.ts
- src/routes/v2/blockchain.ts
- src/routes/v2/control.ts
- src/routes/v2/dataRetrieval.ts
- src/routes/v2/mining.ts
- src/routes/v2/util.ts
Port the following to TS.
* control
* dataRetrieval
* block
* mining
> More TS conversion.

- dist/routes/v2/blockchain.js
- package.json
- src/routes/v2/blockchain.ts
- test/v2/blockchain.js
- test/v2/helpers/panda.js
* pandacash-cli added
* blockchain.js test partly written for v2
> Updates from Panda Cash

- dist/routes/v2/block.js
- dist/routes/v2/services/bitbox.js
- dist/routes/v2/services/requestUtils.js
- src/routes/v2/block.ts
- src/routes/v2/services/bitbox.ts
- src/routes/v2/services/requestUtils.ts
- tsconfig.json
* Added services directory for functions that can be reused across different routes: bitbox, requestUtils
* Restructured block.ts with the use of services from previous point
* Fix of typescript errors (added new lib to tsconfig.json)
> More update from Panda Cash team

- .travis.yml
* Travis CI and Slack integration
>  Add travis ci integration.

- package.json
- src/routes/v2/rawtransactions.ts
- src/routes/v2/route-utils.js
- test/v1/address.js
- test/v2/mocks/raw-transactions-mocks.js
- test/v2/raw-transactions.js
This PR completes the v2 refactor for the Raw Transactions route. It includes unit and integration tests for both.
> Raw Transactions v2 Refactor Complete

- package-lock.json
- package.json
- src/routes/v1/address.js
- src/routes/v1/control.js
- src/routes/v1/dataRetrieval.js
- src/routes/v1/generating.js
- src/routes/v1/mining.js
- src/routes/v1/network.js
- src/routes/v1/payloadCreation.js
- src/routes/v1/rawtransactions.js
- src/routes/v1/slp.js
- src/routes/v1/transaction.js
- src/routes/v2/address.js
- src/routes/v2/dataRetrieval.ts
- src/routes/v2/generating.js
- src/routes/v2/payloadCreation.ts
- src/routes/v2/route-utils.js
- src/routes/v2/transaction.ts
- test/v1/address.js
This PR has two main changes:
- The previous `bitbox-cli` dependency was updated to `bitbox-sdk`
- An  `Address.utxo` endpoint test was failing because the addresses used in that test changed somehow. I pointed the test at a couple new addresses to fix the test.
> Fix BITBOX dependency and test

- .gitignore
- .npmrc
- .travis.yml
- README.md
- package-lock.json
- package.json
This PR switches Travis tests from v1 integration tests to v2 unit tests. It also adds the semantic release dependency needed to automatically release versions of this repository.
> Adding travis changes and package.json changes for semantic release

- test/v2/blockchain.js
Needed to change the vout value.
> fixing the fix for blockchain/gettxout integration test

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- gulpfile.js
- src/routes/v2/address.ts
- swaggerJSONFiles/components.json
- swaggerJSONFiles/fixtures/mainnet/components.json
- swaggerJSONFiles/fixtures/testnet/components.json
- swaggerJSONFiles/paths.json
- swaggerJSONFilesBuilt/mainnet/components.json
- swaggerJSONFilesBuilt/mainnet/paths.json
- swaggerJSONFilesBuilt/testnet/components.json
- swaggerJSONFilesBuilt/testnet/paths.json
- test/v2/address.js
* address/details bulk POST endpoint
> Add Address/details bulk 

- dist/public/swagger-ui-v2.css
- dist/views/swagger-v2.jade
- src/public/swagger-ui-v2.css
- src/views/swagger-v2.jade
- test/v2/block.js
> Payload creation v2

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- src/routes/v2/dataRetrieval.ts
- swaggerJSONFiles/fixtures/mainnet/paths.json
- swaggerJSONFiles/fixtures/testnet/paths.json
- swaggerJSONFiles/paths.json
- swaggerJSONFilesBuilt/mainnet/paths.json
- swaggerJSONFilesBuilt/testnet/paths.json
> Rest v2 updates

- src/routes/v2/address.ts
- src/routes/v2/block.ts
- src/routes/v2/logging.js
- src/routes/v2/route-utils.js
- test/v2/address.js
- test/v2/block.js
- test/v2/blockchain.js
- test/v2/data-retrieval.js
- test/v2/mining.js
- test/v2/payload-creation.js
- test/v2/raw-transactions.js
- test/v2/util.js
Bulk Tests for Address and Block route libraries.
> Bulk Tests for Address and Block route libraries.

- package-lock.json
- src/routes/v2/blockchain.ts
- test/v2/blockchain.js
- test/v2/control.js
- test/v2/mocks/blockchain-mock.js
This PR includes some tests for the blockchain bulk endpoints. But primarily it contains a fix for the Control route integration test.
> Fix Control route integration test

- .gitignore
- src/routes/v2/rawtransactions.ts
- test/v2/raw-transactions.js
Refactors the Bulk endpoints for `getRawTransaction` and `decodeRawTransaction`. Adds unit and integration tests for these changes.
> V2 Bulk changes to getRawTransaction and decodeRawTransaction

- README.md
- src/routes/v2/slp.ts
> Increase slp txid validate 

- src/routes/v2/util.ts
- test/v2/util.js
This is the last bulk endpoint to be refactored, with tests added.
> Refactored util.validateAddressBulk. Added unit and integration tests

- src/routes/v2/transaction.ts
transaction.detailsBulk: now makes Insight API calls in parallel
> transaction.detailsBulk: now makes Insight API calls in parallel

- package-lock.json
- test/v2/slp.js
Woke up this morning to a broken `stage` branch. This PR makes the following changes:
- Commented out the unit test for the SLP `list` endpoint, which lists all tokens. This endpoint is in flux is not ready for a unit test at this time.
The above changes allowed all the unit tests to pass.
> CT: Fix Stage

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package-lock.json
- package.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- test/v2/slp.js
* Format tokens locally to resolve issue w/ /list failing after new/unconfirmed token is created.
> Format tokens.

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- test/v2/slp.js
Return all valid slp genesis properties:
* id
* timestamp
* symbol
* name
* documentUri
* documentHash
* decimals
* initialTokenQty
> Add slp properties

- README.md
- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- src/routes/v2/rawtransactions.ts
- src/routes/v2/slp.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- test/v2/raw-transactions.js
> fix(decodeScript Bulk): Adding bulk POST endpoint for decodeScript

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package-lock.json
- package.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/components.json
- swaggerJSONFiles/fixtures/mainnet/components.json
- swaggerJSONFiles/fixtures/testnet/components.json
- swaggerJSONFiles/info.json
- swaggerJSONFiles/paths.json
- swaggerJSONFilesBuilt/mainnet/components.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/mainnet/paths.json
- swaggerJSONFilesBuilt/testnet/components.json
- swaggerJSONFilesBuilt/testnet/info.json
- swaggerJSONFilesBuilt/testnet/paths.json
- test/v2/slp.js
This PR fulfills Issue #291. It has the following features:
- Adds a new POST `slp/convert` endpoint for bulk conversion of addresses.
- Adds unit tests for this new endpoint.
- Adds a Swagger UI entry for this new entry point
- Bumps the minor version of rest
> SLP bulk convert

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package-lock.json
- package.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
* Return balance 0 and decimals for tokens w/ no balance.
> Slp balance update

- src/routes/v2/slp.ts
- test/v2/slp.js
> Addresses by tokenid

- dist/middleware/auth.js
- dist/middleware/route-ratelimit.js
- src/middleware/auth.js
- src/middleware/route-ratelimit.ts
- test/v2/mocks/express-mocks.js
- test/v2/rate-limits.js
A lot of code, including the edited rate limiting and unit tests were deleted by the code revert yesterday. This PR adds this code back in.
Tests are passing. Manual testing was done to ensure everything is working.
> Replace missing rate-limiting and auth code

- test/v2/integration/rate-limits.js
Create a rate-limit integration test. This test is passing against a local instance of rest, but is not passing against the stage server. We need to make sure we are using the right password.
> rate-limits.js integration test

- src/routes/v2/address.ts
- src/routes/v2/block.ts
- src/routes/v2/blockchain.ts
- src/routes/v2/rawtransactions.ts
- src/routes/v2/route-utils.js
- src/routes/v2/slp.ts
- src/routes/v2/transaction.ts
- test/v2/address.js
- test/v2/raw-transactions.js
- test/v2/slp.js
This PR reinstates some code that was pulled out during the revert of the PR that implemented pro-tier rate limits. Specifically this PR fixes these two GitHub Issues:
https://github.com/Bitcoin-com/bitbox-sdk/issues/74
https://github.com/Bitcoin-com/rest.bitcoin.com/issues/330
> Improved Array-size Rate Limit Error Handling

- .gitignore
- dist/util/winston-logging.js
- logs/README.md
- package-lock.json
- package.json
- src/routes/v2/address.ts
- src/util/winston-logging.js
A permissions error on the staging server required a roll-back of the code. Trying local logging again now that the permissions error is 'fixed'.
> Local Logging pt 2

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package-lock.json
- package.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- test/v2/slp.js
Reverts Bitcoin-com/rest.bitcoin.com#372
> Revert "Rollback balances"

- src/routes/v2/block.ts
- src/routes/v2/rawtransactions.ts
- test/v2/block.js
A couple minor tweaks to the error logging, to reduce noise.
> Minor tweek to logging

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
* Old version of SLP SDK was using the local validator incorrectly which was causing time outs
* Replace w/ the latest and greatest SLP SDK.
> Bump SLP SDK version.

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- yarn.lock
cashaccount lib 0.3.3 to get error messages.
> bump cashaccounts lib v.

- README.md
Reverts Bitcoin-com/rest.bitcoin.com#446
> Revert "Force deploy."

- package.json
- src/app.ts
- src/middleware/route-ratelimit.ts
- swaggerJSONFiles/info.json
- yarn.lock
Reverts Bitcoin-com/rest.bitcoin.com#445
> Revert "Testing websockets on stage"

- dist/app.js
- src/app.ts
- yarn.lock
Updates the 'morgan' logger to also log IP addresses to the console, which gets recorded in the syslog on the production server.
> Log IP Addresses

- src/app.ts
Logs user agent in addition to IP address.
> Adding user-agent

- dist/app.js
- dist/middleware/req-logging.js
- dist/util/winston-logging.js
- src/app.ts
- src/middleware/req-logging.ts
- src/util/winston-logging.js
Major features in this PR:
- Retrieving metadata from the request object like IP address, user-agent Header, url requested, etc, and logging it to a local log file using Winston.
- Winston configured to save 20x 1 megabyte files, then overwrite them as new log files come in. This prevents run-away logging that could crash the server.
> Better Logging

- dist/app.js
- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- src/app.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
Reverts Bitcoin-com/rest.bitcoin.com#461
> Revert "Reenable websockets."

- dist/app.js
- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- src/app.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
Reverts Bitcoin-com/rest.bitcoin.com#462
> Reenable websockets.

- src/routes/v2/address.ts
- src/routes/v2/route-utils.js
* This addresses [Issue 437](https://github.com/Bitcoin-com/rest.bitcoin.com/issues/437)
> Network Error Handling updated to handle SLP addresses

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/components.json
- swaggerJSONFiles/paths.json
- swaggerJSONFilesBuilt/mainnet/components.json
- swaggerJSONFilesBuilt/mainnet/paths.json
- swaggerJSONFilesBuilt/testnet/components.json
- swaggerJSONFilesBuilt/testnet/paths.json
- test/v2/slp.js
This addresses [Issue 322](https://github.com/Bitcoin-com/rest.bitcoin.com/issues/322)
> Bulk slp balances for address.

- src/routes/v2/slp.ts
- test/v2/slp.js
- yarn.lock
> Fixed unit tests

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- src/routes/v2/slp.ts
- swaggerJSONFiles/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- test/v2/slp.js
- yarn.lock
* Change slpdb query to request token by tokenid instead of all tokens and then looping over them. Makes request much snappier.
> Update query to make call quicker.

- src/routes/v2/slp.ts
- test/v2/slp.js
- Fixes the unit tests
- Adds an integration test
- Removes the redundant `transactionsFromInsight()` call
> Fixes tests, removed redundant code.

- test/v2/control.js
- test/v2/mocks/util-mocks.js
- test/v2/util.js
Fixes failing integration tests. Addresses Issue #527
> Fix integration tests

- src/routes/v2/address.ts
- src/routes/v2/block.ts
- src/routes/v2/blockchain.ts
- src/routes/v2/rawtransactions.ts
- src/routes/v2/route-utils.js
- src/routes/v2/slp.ts
- test/v2/slp.js
create axios instance and add conservative timeout defaults
replaces https://github.com/Bitcoin-com/rest.bitcoin.com/pull/549
> add timeout

- src/routes/v2/slp.ts
- test/v2/mocks/slp-mocks.js
- test/v2/slp.js
Updated queries for new schema.
Resolves #547
> Update SLPDB queries to prepare for 1.0 release

- src/routes/v2/interfaces/ISlpData.ts
- src/routes/v2/services/slpdb.ts
- src/routes/v2/slp.ts
- test/v2/mocks/slp-mocks.js
- test/v2/slp.js
- Update token stats endpoints for SLPDB 1.0 compability
- Setup structure for SlpData based compatible services such as SLPDB and SLP Java Indexer
> Update token stats endpoints for SLPDB 1.0 compability

- src/routes/v2/interfaces/ISlpData.ts
- src/routes/v2/services/slpdb.ts
- src/routes/v2/slp.ts
- test/v2/mocks/slp-mocks.js
- test/v2/slp.js
- Add mint, burned, and circulating supply fields
- Cleanup unused method
> Update slp list endpoint

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- src/routes/v2/interfaces/ISlpData.ts
- src/routes/v2/services/slpdb.ts
- src/routes/v2/slp.ts
- swaggerJSONFiles/components.json
- swaggerJSONFiles/paths.json
- swaggerJSONFilesBuilt/mainnet/components.json
- swaggerJSONFilesBuilt/mainnet/paths.json
- swaggerJSONFilesBuilt/testnet/components.json
- swaggerJSONFilesBuilt/testnet/paths.json
- test/v2/slp.js
- Support fromBlock parameter to exclude already seen transactions
- Normalize result format
- Update swagger docs
> Update SLP transaction history endpoints

- dist/public/bitcoin-com-mainnet-rest-v2.json
- dist/public/bitcoin-com-testnet-rest-v2.json
- package.json
- swaggerJSONFiles/fixtures/mainnet/info.json
- swaggerJSONFiles/fixtures/testnet/info.json
- swaggerJSONFilesBuilt/mainnet/info.json
- swaggerJSONFilesBuilt/testnet/info.json
- yarn.lock
- remove link to chatroom (discontinuing)
- added graceful-fs to package.json resolutions to fix build errors with node v11+
> remove chatroom link. add resolution for node v11+
