Bitcoin-com/rest.bitcoin.com

.editorconfig, .eslintrc.json, .gitignore, .npmrc, .travis.yml, README.md, package.json, routes/address.js, test/address.js
This PR adds the following:
* It adds `coveralls` as an NPM dependency for when we're ready to plug into that system.
* Removes `nyc` from the test to speed up unit tests in Travis CI. Coverage reporting is run *after* tests have passed.
* Adds a script to generate html coverage reports.
* Adds eslint and Prettier rules for auto-linting in the Atom text editor.
=> Adding Linting Rules and Auto-Linting

public/bitcoin-com-rest-v1.json, routes/blockchain.js
The list of transactions can get very long if the blocks are big. Usually people just want basic info about the block, such as the size. This will be helpful to reduce latency for applications after a block is found.
=> Option to remove transaction hash list from /blockchain/getBlock

routes/address.js, test/address.js
I realized this morning that the CURL commands on the page served by rest.bitcoin.com were no longer working. I adjusted the code to align with the existing documentation and expected behavior. 
This also included expanding the behavior of the `/details/:address` endpoint to accept non-array input. This PR also includes a test for that behavior.
=> Updates to bring behavior into alignment with documentation.

routes/rawtransactions.js
I'm running Bitcoin Unlimited 1.5.0.0 and I'm getting the error `JSON value is not an integer as expected` now with getRawTransaction. Changing the verbose variable to an integer fixes it, since the actual rpc command takes an integer. I haven't tested this with any other node version.
=> Change verbose to integer for getRawTransaction

package.json, test/v2/helpers/panda.js
For testing of the replaced library, run:
npm run test-v2:blockchain
=> pandacash-cli replaced with pandacash-core

.gitignore, src/routes/v2/address.ts, src/routes/v2/transaction.ts, test/v2/address.js, test/v2/transaction.js
After discussing the pros and cons and length, @SpendBCH and I decided that the best past forward for the V2 refactor is to keep the GET endpoints for Insight API calls, but restrict them to single item calls (address, utxo, tx, etc). This maintains the nice swagger UI, URL execution in a browser, and 'friendly' looking endpoint.
The new POST endpoints are maintained. It's still possible to make the call with 1 to 20 elements, but the inputs must be in the *body* (vs the GET parameters), and the input must be an array.
The outputs are also different. GET calls return a single item, whereas POST calls will return an array of items.
=> GET and POST endpoints added for Insight API Calls

test/v2/blockchain.js
This PR fixes the failing integration test for the `blockchain/gettxout()` endpoint. The reason the test was failing is because something happened to the UTXO attached to the TXID that was originally used. I fixed it by creating a new wallet and sending some tBCH to in from the faucet. I then destroyed the wallet so that the UTXO will never change.
=> Fixing gettxout integration tests

dist/public/bitcoin-com-mainnet-rest-v2.json, dist/public/bitcoin-com-testnet-rest-v2.json, swaggerJSONFiles/paths.json, swaggerJSONFilesBuilt/mainnet/paths.json, swaggerJSONFilesBuilt/testnet/paths.json
* /rawtransactions/sendRawTransaction/{hex}
* /rawtransactions/create/{inputs}/{outputs}
* /rawtransactions/change/{rawTx}/{prevTxs}/{destination}/{fee}
* /rawtransactions/input/{rawTx}/{txid}/{n}
* /rawtransactions/opReturn/{rawTx}/{payload}
* /rawtransactions/reference/{rawTx}/{destination}
=> fix(restv2): expose raw transaction endpoints in swagger.

src/routes/v2/address.ts, test/v2/address.js
The output of the bulk unconfirmed endpoint was returning data that was incorrect and very different from the single unconfirmed endpoint. This PR fixes that problem. Verifies that single and bulk are now output the same data.
=> Fixes problem with bulk Address.unconfirmed endpoint

package-lock.json, src/routes/v2/rawtransactions.ts, test/v2/e2e/address.js, test/v2/raw-transactions.js
Been working this morning on the POST sendRawTransaction endpoint. Getting some errors, and they are caused by the full node. Here is the summary:
1. Making parallel RPC calls to the full nodes `sendrawtransaction` endpoint will return the same TXID with different input TX hexes.
I created a branch called `ct-send-rawtransactions-parallel-not-working` illustrating the parallelization code that causes this behavior here:
https://github.com/Bitcoin-com/rest.bitcoin.com/blob/ct-send-rawtransactions-parallel-not-working/src/routes/v2/rawtransactions.ts#L507-L519
This behavior persists weather I send two TXs off the same UTXO, or if I use two UTXOs. Running this call in parallel is not possible.
2. Making series RPC calls will result in the full node returning the error: `258: …
=> Fixing bulk sendrawtransaction

dist/public/bitcoin-com-mainnet-rest-v2.json, dist/public/bitcoin-com-testnet-rest-v2.json, src/routes/v2/address.ts, swaggerJSONFilesBuilt/mainnet/info.json, swaggerJSONFilesBuilt/testnet/info.json, test/v2/address.js, test/v2/mocks/address-mock.js
the `/addr` Insight API call returns two incorrectly spelled properties: `txApperances` and `unconfirmedTxApperances`
We don't have any control over the data coming from Insight API, so we have no control over the proper spelling of these properties. A previous commit corrected the spelling and broke the integration tests. Unit tests still passed, because the mocks were updated with the correct spelling, which is why the CI didn't catch it.
This PR corrects the code by replacing the misspelled properties. Integration tests are now passing again.
=> Replacing misspelled property coming from Insight

dist/public/bitcoin-com-mainnet-rest-v2.json, dist/public/bitcoin-com-testnet-rest-v2.json, swaggerJSONFiles/paths.json, swaggerJSONFilesBuilt/mainnet/paths.json, swaggerJSONFilesBuilt/testnet/paths.json
The scope of this PR is to add a bulk endpoint for getRawTransactions in the Swagger UI. Addresses Issue #233 
---
This PR has part of the UI  implemented, but it's acting funny: 
- Clicking on the POST (bulk) call will open both the POST and GET calls.
- I'm also not sure how to add the verbose flag to the POST call.
=> Fix getRawTransactions Bulk in Swagger UI

src/routes/v2/slp.ts, test/v2/mocks/slp-mocks.js, test/v2/slp.js
This PR currently has the following changes:
- Reenables the unit test for `slp/list` endpoint. Unit and integration tests both pass.
=> Fixing unit test for slp

package-lock.json, package.json, tsconfig.json
TS was having issues because slpjs is transpiled to es6, not es5.  So when your comiles it fails due to:
1)  `"allowImplicityAny": false`, -- Relatively harmless to change to true
2) `"libs"` needs "es2017" due to slpjs use of new language features
3) `"downlevelIteration"` needs set to true due to use of `for..of` operator.  I'm not sure if a web version of this would need some shim or not. [see here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#downlevelIteration)
=> tsconfig.json update

README.md, dist/app.js, dist/middleware/route-ratelimit.js, dist/public/bitcoin-com-mainnet-rest-v2.json, dist/public/bitcoin-com-testnet-rest-v2.json, package-lock.json, package.json, src/app.ts, src/middleware/route-ratelimit.ts, src/routes/v2/address.ts, src/routes/v2/block.ts, src/routes/v2/blockchain.ts, src/routes/v2/control.ts, src/routes/v2/generating.js, src/routes/v2/health-check.js, src/routes/v2/index.js, src/routes/v2/mining.ts, src/routes/v2/network.ts, src/routes/v2/rawtransactions.ts, src/routes/v2/slp.ts, src/routes/v2/transaction.ts, src/routes/v2/util.ts, swaggerJSONFiles/info.json, swaggerJSONFilesBuilt/mainnet/info.json, swaggerJSONFilesBuilt/testnet/info.json
Only changes /v2 routes
Default rate limit is 60
Rate limit can be specified with env var RATE_LIMIT_MAX_REQUESTS
Setting RATE_LIMIT_MAX_REQUESTS=0 will disable rate limiting on v2 routes
=> rate limit by middleware for future auth

dist/public/bitcoin-com-mainnet-rest-v2.json, dist/public/bitcoin-com-testnet-rest-v2.json, package.json, src/routes/v2/rawtransactions.ts, swaggerJSONFiles/info.json, swaggerJSONFilesBuilt/mainnet/info.json, swaggerJSONFilesBuilt/testnet/info.json, test/v2/raw-transactions.js
This PR addresses Issue #273 by adding a GET call for the `/rawTransactions/sendRawTransaction/:hex` endpoint. The behavior of the POST endpoint remains unchanged. This PR adds unit and integration tests for the new endpoint.
=> fix(sendRawTransaction): Adding GET /rawTransactions/sendRawTransaction/:hex endpoint

dist/public/bitcoin-com-mainnet-rest-v2.json, dist/public/bitcoin-com-testnet-rest-v2.json, src/routes/v2/slp.ts, swaggerJSONFiles/components.json, swaggerJSONFiles/fixtures/mainnet/components.json, swaggerJSONFiles/fixtures/testnet/components.json, swaggerJSONFiles/paths.json, swaggerJSONFilesBuilt/mainnet/components.json, swaggerJSONFilesBuilt/mainnet/paths.json, swaggerJSONFilesBuilt/testnet/components.json, swaggerJSONFilesBuilt/testnet/paths.json, test/v2/slp.js
This PR fulfills PR #266. It includes these features:
- Adds a POST endpoint for `slp/list` where the `tokenIds` can be passed as an array
- Added unit and integration tests for this new endpoint
- Updates the Swagger UI.
Adding the POST entry for `slp/list` seems to have removed the GET `slp/list` entry from the Swagger UI. This needs to be looked at.
=> SLP bulk list by ID

package-lock.json, package.json, src/routes/v2/slp.ts, test/v2/mocks/slpjs-mocks.js, test/v2/slp.js
This PR finishes building out the missing unit tests for the existing SLP endpoints. The trick was mocking the slpjs library using a new mocking library called proxyquire.
=> Fix SLP unit tests

dist/middleware/auth.js, src/middleware/auth.js
This PR enables multiple pro-tier passwords. Passwords are set by the environment variable `PRO_PASS`. Passwords are separated by a colon. Example:
`PRO_PASS=pass1:pass2:pass3`
=> Multiple pro-tier password

src/routes/v2/address.ts, src/routes/v2/block.ts, src/routes/v2/route-utils.js, src/routes/v2/transaction.ts, test/v2/transaction.js
Endpoints like `transactions/detailsBulk()` were inappropriately handling errors and causing a lot of noise in the error logs. This PR makes a slight tweek to the error handling for these calls. It reduces noise in the error logs. Unit tests were updated to reflect these changes.
=> Tweek to Error Logs

src/routes/v2/slp.ts, test/v2/mocks/slp-mocks.js, test/v2/slp.js
This PR fixes the SLP integration tests that were failing:
- The listSingleToken() tests were failing because of a mismatch with the mock file. This was causing unit tests to pass, but integration tests to fail. I aligned the mocking file so that both tests pass now.
- The txsTokenIdAddressSingle() endpoint does not appear to work on testnet. The trest.bitcoin.com swagger UI always returns an empty array, even for valid data. It does appear to work on rest.bitcoin.com, but the integration tests target testnet, so that doesn't help. This integration test was commented out until we can evaluate why this SLPDB query does not return any data on testnet.
=> Fix SLP Tests

src/routes/v2/transaction.ts
This PR addresses Issue #384. It adds a cashAddr array to the vout object in transaction details. That way users can easily get the cash address from the inputs AND the outputs.
=> Added cashaddr to vout in transaction.details

dist/app.js, src/app.ts
404 error handling was returning `[Object object]` on the command line. This PR fixes the error handling to return appropriate data to the user and on the command line.
=> Fix 404 Error Handling

src/routes/v2/slp.ts
Went through each function in the slp.ts route library and added a line to log the error message to our Winston local logs. 
Only added to functions wrapped in a try/catch statements. There are several functions in that library not wrapped in try/catch statements.
=> Added local logging to all catch statement in slp.ts

src/middleware/auth.js
Whenever someone uses a pro-tier hard-coded token for an API call to unlock pro-tier rate limits, it gets logged to the local logging. This was done so that we could see when people started to use pro-tier tokens. Now that people are using them, it's clogging up the logs and preventing us from seeing legit errors.
This PR removes the logging of pro-tier API calls, so that the logs are easier to read.
=> Removing logging when pro-tier token is used

src/app.ts, src/middleware/req-logging.ts, src/util/winston-logging.js
- Increases the local logging cache to 100 megabytes. I've run tests to ensure that old logs are overwritten by new logs, once the maximum size for log files is reached.
- Switches the logging level to 'verbose', which is in-between 'debug' and 'info'. Can turn off local logging of connection information by changing logging level to 'info'.
=> Refining local logging code after tests

dist/app.js, package.json, src/app.ts, yarn.lock
Adds the [wtfnode](https://www.npmjs.com/package/wtfnode) package to the dev dependencies. It logs data about the node.js event loop every 5 minutes to the local logs. This will hopefully help us get a handle the increase in CPU usage over time.
=> Incorporating wtfnode to monitor event loop in logs

src/routes/v2/control.ts, test/v2/control.js, test/v2/mocks/control-mock.js
The `getInfo` JSON RPC call has been deprecated in the ABC v0.19.08 full node implementation. This PR adds the `getNeworkInfo` RPC call to the Control route. This is the only functional RPC call that will report the version of the currently running node.
This PR also includes unit and integration tests. Once this PR is merged into stage, I'll add an endpoint to BITBOX SDK to call it.
=> Adding getNetworkInfo RPC call

test/v2/slp.js
The SLP address being used in an integration tests lost its funds somehow which caused the integration test to fail. A new address was created with new tokens and that address is being used now. This fixes the test.
=> Fix failing SLP integration test

dist/app.js, dist/middleware/auth.js, src/app.ts, src/middleware/auth.js, src/routes/v2/slp.ts, yarn.lock
This PR adds a [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) header to each call to SLPDB in the slp.ts route library. This enables rest to talk to its own private instance of SLPDB. See [this gist](https://gist.github.com/christroutner/fc717ca704dec3dded8b52fae387eab2) for additional details.
The authentication password is set by `SLPDB_PASS` environment variable, and defaults to `BITBOX`.
=> Basic Auth for private SLPDB

src/app.ts, src/routes/v2/slp.ts, test/v2/slp.js
This PR contains improved error handling for the SLP `txDetails()` endpoint. In reviewing our production error logs, this error occurs thousands of times per day:
```
Opening file main-prod-all.log
opening this file: /home/safeuser/rest-logs/src/commands/../../logs/main-prod-all.log
Error report:
Cnt: 57144
Msg: Error in slp.ts/txDetails().Cannot read property 'in' of undefined
stack trace: TypeError: Cannot read property 'in' of undefined
at /var/www/rest.bitcoin.com/dist/routes/v2/slp.js:1924:34
at step (/var/www/rest.bitcoin.com/dist/routes/v2/slp.js:43:23)
at Object.next (/var/www/rest.bitcoin.com/dist/routes/v2/slp.js:24:53)
at /var/www/rest.bitcoin.com/dist/routes/v2/slp.js:18:71
at new Promise (<anonymous>)
at __awaiter (/var/www/rest.bitcoin.com/dist/routes/v2/slp.js:14:12)
at …
```
=> fix(txdetails): Improved error handling for txdetails

dist/app.js, package.json, src/routes/v2/slp.ts, yarn.lock
This PR removes LevelDB as a dependency and returns rest to a stateless application. This means it can be scaled more effectively using [pm2 cluster mode](https://pm2.keymetrics.io/docs/usage/cluster-mode/).
Only the last commit with the message `Removing level DB` which contains changes to the `slp.ts` library are part of this PR. The other commits in this PR already exist within the `master` branch, but have not yet been incorporated into the `stage` branch.
=> Remove level DB

src/routes/v2/slp.ts
Fixes a typo that was preventing axios from timing out properly on slp endpoints.
=> fix(slp timeout): Fixing timout for axios for slp endpoints

docs/v3/api-spec.md, src/routes/v3/address-new.js, src/routes/v3/services/blockbook.js, src/routes/v3/services/ninsight.js, test/v3/integration/blockbook.integration.js, test/v3/integration/ninsight.integration.js, test/v3/mocks/address-mock.js, test/v3/mocks/blockbook-mock.js, test/v3/mocks/ninsight-mock.js, test/v3/unit/address.unit.js, test/v3/unit/blockbook.unit.js, test/v3/unit/ninsight.unit.js
Includes integration tests and 100% unit test coverage.
To test:
`curl -X POST "http://localhost:3000/v3-alpha/address/utxo" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"addresses\":[\"bitcoincash:qp3sn6vlwz28ntmf3wmyra7jqttfx7z6zgtkygjhc7\",\"bitcoincash:qpdh9s677ya8tnx7zdhfrn8qfyvy22wj4qa7nwqa5v\"]}"`
=> v3 Address Utxo Route

src/routes/v2/address.ts, src/routes/v2/mining.ts, src/routes/v2/slp.ts, src/routes/v3/address.ts, src/routes/v3/mining.ts
This utitlizes the `toString` method of the query parser to extract a string value from the request parameters. This resolves #574 
https://expressjs.com/en/api.html#req.query
=> use toString method to retrieve proper type
